color0 #dfe1f9
color1 #ba1a1a
color2 #006783
color3 #106681
color4 #505b92
color5 #007ca0
color6 #357b98
color7 #191b25
color8 #73768b
color9 #ba1a1a
color10 #006783
color11 #106681
color12 #505b92
color13 #007ca0
color14 #357b98
color15 #191b25

cursor                #191b25
cursor_text_color     #fbf8ff
background            #fbf8ff
foreground            #191b25
selection_foreground  #434659
selection_background  #dfe1f9
active_border_color   #006783
inactive_border_color #dfe1f9
url_color             #006783

active_tab_foreground   #ffffff
active_tab_background   #006783
inactive_tab_foreground #434659
inactive_tab_background #dfe1f9
cursor_trail_color      #434659
