color0 #000000
color1 #ea6c6d
color2 #6cbf43
color3 #eca944
color4 #3199e1
color5 #9e75c7
color6 #46ba94
color7 #bababa
color8 #686868
color9 #f07171
color10 #86b300
color11 #f2ae49
color12 #399ee6
color13 #a37acc
color14 #4cbf99
color15 #d1d1d1
background #f8f9fa
selection_foreground #f8f9fa
cursor #ffaa33
cursor_text_color #f8f9fa
foreground #42474c
selection_background #035bd6
active_border_color #ff8f40
inactive_border_color #86b300

active_tab_foreground   #f8f9fa
active_tab_background   #ff8f40
inactive_tab_foreground #6e757c
inactive_tab_background #e4e6e9
cursor_trail_color      #6e757c
