color0 #aec8e0
color1 #a24a5b
color2 #0a68b3
color3 #a3293e
color4 #572d86
color5 #175082
color6 #7e1b2c
color7 #181a1b
color8 #6e859a
color9 #a24a5b
color10 #0a68b3
color11 #a3293e
color12 #572d86
color13 #175082
color14 #7e1b2c
color15 #181a1b

cursor                #181a1b
cursor_text_color     #dae6f1
background            #dae6f1
foreground            #181a1b
selection_foreground  #4f5257
selection_background  #aec8e0
active_border_color   #2277c3
inactive_border_color #aec8e0
url_color             #2277c3

active_tab_foreground   #fafbfb
active_tab_background   #2277c3
inactive_tab_foreground #4f5257
inactive_tab_background #aec8e0
cursor_trail_color      #4f5257
