palette = "noctalia"
format = """
╭─ $directory$git_branch$git_status $fill $direnv$nix_shell $fill $username$hostname$shell
╰$character
"""

[fill]
symbol = " "

[character]
success_symbol = "─"
error_symbol = "[✗](red)"

[username]
style_user = "fg:crust bg:green"
style_root = "fg:red bg:green bold"
disabled = false
show_always = true
format = "[](fg:green)[ $user](fg:crust bg:green)($style)[](fg:green)"

[hostname]
format = "[](fg:red)[ $hostname](fg:crust bg:red)[](fg:red)"
ssh_only = false

[directory]
fish_style_pwd_dir_length = 1
read_only = "󰌾 "
format = "[](fg:magenta)[$path](fg:crust bg:magenta)[](fg:magenta)"

[git_branch]
format = "[](fg:yellow)[$symbol$branch(:$remote_branch)](fg:crust bg:yellow)"
symbol = " "

[git_status]
format = "[$all_status](fg:crust bg:yellow)[](fg:yellow)"

[line_break]
disabled = true

[shell]
disabled = false
format = "[](fg:cyan)[󱆃 $indicator](fg:crust bg:cyan)[](fg:cyan)"

[direnv]
disabled = false
format = " direnv $loaded"

[python]
disabled = false
format = " py $version $virtualenv"

[nix_shell]
disabled = false
format = " nix $name$state"






















































































# >>> NOCTALIA STARSHIP PALETTE >>>
# Noctalia Starship Palette (predefined colorscheme)
# Generated by Noctalia - do not edit manually

[palettes.noctalia]
# Standard colors
blue      = "#56949f"
red       = "#b4637a"
green     = "#286983"
yellow    = "#ea9d34"
cyan      = "#d7827e"
magenta   = "#907aa9"
white     = "#575279"
black     = "#f2e9e1"

# Extended palette (Catppuccin-compatible names)
rosewater = "#ea9d34"
flamingo  = "#b4637a"
pink      = "#907aa9"
mauve     = "#907aa9"
maroon    = "#b4637a"
peach     = "#ea9d34"
teal      = "#d7827e"
sky       = "#d7827e"
sapphire  = "#56949f"
lavender  = "#907aa9"

# Text shades
text      = "#575279"
subtext1  = "#575279"
subtext0  = "#9893a5"

# Surface shades
overlay2  = "#9893a5"
overlay1  = "#9893a5"
overlay0  = "#f2e9e1"
surface2  = "#f2e9e1"
surface1  = "#f2e9e1"
surface0  = "#faf4ed"
base      = "#faf4ed"
mantle    = "#faf4ed"
crust     = "#faf4ed"
# <<< NOCTALIA STARSHIP PALETTE <<<
