palette = "noctalia"
format = """
╭─ $directory$git_branch$git_status $fill $direnv$nix_shell $fill $username$hostname$shell
╰$character
"""

[fill]
symbol = " "

[character]
success_symbol = "─"
error_symbol = "[✗](red)"

[username]
style_user = "fg:crust bg:green"
style_root = "fg:red bg:green bold"
disabled = false
show_always = true
format = "[](fg:green)[ $user](fg:crust bg:green)($style)[](fg:green)"

[hostname]
format = "[](fg:red)[ $hostname](fg:crust bg:red)[](fg:red)"
ssh_only = false

[directory]
fish_style_pwd_dir_length = 1
read_only = "󰌾 "
format = "[](fg:magenta)[$path](fg:crust bg:magenta)[](fg:magenta)"

[git_branch]
format = "[](fg:yellow)[$symbol$branch(:$remote_branch)](fg:crust bg:yellow)"
symbol = " "

[git_status]
format = "[$all_status](fg:crust bg:yellow)[](fg:yellow)"

[line_break]
disabled = true

[shell]
disabled = false
format = "[](fg:cyan)[󱆃 $indicator](fg:crust bg:cyan)[](fg:cyan)"

[direnv]
disabled = false
format = " direnv $loaded"

[python]
disabled = false
format = " py $version $virtualenv"

[nix_shell]
disabled = false
format = " nix $name$state"

# >>> NOCTALIA STARSHIP PALETTE >>>
# Noctalia Starship Palette
# Generated by Noctalia - do not edit manually

[palettes.noctalia]
# Standard colors
blue      = "#a9aefe"
red       = "#fd4663"
green     = "#9bfece"
yellow    = "#fff59b"
cyan      = "#9bfece"
magenta   = "#fd4663"
white     = "#f3edf7"
black     = "#11112d"

# Extended palette (Catppuccin-compatible names)
rosewater = "#fff59b"
flamingo  = "#fd4663"
pink      = "#fd4663"
mauve     = "#fd4663"
maroon    = "#fd4663"
peach     = "#fff59b"
teal      = "#9bfece"
sky       = "#9bfece"
sapphire  = "#a9aefe"
lavender  = "#fd4663"

# Text shades
text      = "#f3edf7"
subtext1  = "#f3edf7"
subtext0  = "#21215f"

# Surface shades
overlay2  = "#21215f"
overlay1  = "#21215f"
overlay0  = "#11112d"
surface2  = "#11112d"
surface1  = "#11112d"
surface0  = "#070722"
base      = "#070722"
mantle    = "#070722"
crust     = "#070722"
# <<< NOCTALIA STARSHIP PALETTE <<<
