#
# Basics:
#
# Start a terminal
bindsym $mod+Return exec $term

# Start your launcher
bindsym $mod+Space exec shell-ipc spotlight toggle

# Apps
bindsym $mod+n exec nautilus
bindsym $mod+w exec flatpak run io.gitlab.librewolf-community
bindsym $mod+t exec flatpak run org.mozilla.Thunderbird
bindsym $mod+e exec flatpak run org.gnome.TextEditor

# DMS features
bindsym $mod+comma exec shell-ipc settings focusOrToggle
bindsym $mod+y exec shell-ipc dankdash wallpaper
bindsym $mod+m exec shell-ipc processlist focusOrToggle
bindsym $mod+Shift+n exec shell-ipc notifications toggle
bindsym $mod+v exec shell-ipc clipboard toggle

# Lockscreen
bindsym $mod+Mod1+l exec shell-ipc lock lock

# Desktop portal
exec /usr/libexec/xdg-desktop-portal -r

#
# Screen capture:
#

# Send to both file and clipboard
bindsym Print exec ~/.local/bin/screen_full.sh
bindsym Mod1+Print exec ~/.local/bin/screen_win.sh
bindsym $mod+Print exec ~/.local/bin/screen_zone.sh

#
# Multimedia
#
bindsym XF86AudioRaiseVolume exec wpctl set-volume @DEFAULT_AUDIO_SINK@ 3%+
bindsym XF86AudioLowerVolume exec wpctl set-volume @DEFAULT_AUDIO_SINK@ 3%-
bindsym XF86AudioMute exec wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindsym XF86AudioPlay exec playerctl play-pause
bindsym XF86AudioNext exec playerctl next
bindsym XF86AudioPrev exec playerctl previous
bindsym XF86AudioStop exec playerctl stop
bindsym XF86MonBrightnessUp exec brightnessctl set 5%+
bindsym XF86MonBrightnessDown exec brightnessctl set 5%-

