color0 #1c1016
color1 #ffb4ab
color2 #cfbdff
color3 #cfbdfe
color4 #fcb0d6
color5 #cfbdff
color6 #cfbdfe
color7 #f3dde5
color8 #a78896
color9 #ffb4ab
color10 #cfbdff
color11 #cfbdfe
color12 #fcb0d6
color13 #cfbdff
color14 #cfbdfe
color15 #f3dde5

cursor                #f3dde5
cursor_text_color     #1c1016
background            #1c1016
foreground            #f3dde5
selection_foreground  #dfbdcc
selection_background  #58404c
active_border_color   #cfbdff
inactive_border_color #58404c
url_color             #cfbdff

active_tab_foreground   #371e72
active_tab_background   #cfbdff
inactive_tab_foreground #dfbdcc
inactive_tab_background #58404c
cursor_trail_color      #dfbdcc
