color0 #131313
color1 #ffb4ab
color2 #86ceff
color3 #b7c9d8
color4 #cdc0e9
color5 #86ceff
color6 #b7c9d8
color7 #e2e2e2
color8 #919191
color9 #ffb4ab
color10 #86ceff
color11 #b7c9d8
color12 #cdc0e9
color13 #86ceff
color14 #b7c9d8
color15 #e2e2e2

cursor                #e2e2e2
cursor_text_color     #131313
background            #131313
foreground            #e2e2e2
selection_foreground  #c6c6c6
selection_background  #474747
active_border_color   #86ceff
inactive_border_color #474747
url_color             #86ceff

active_tab_foreground   #00344c
active_tab_background   #86ceff
inactive_tab_foreground #c6c6c6
inactive_tab_background #474747
cursor_trail_color      #c6c6c6
