color0 #0c141b
color1 #ffb4ab
color2 #50dbcf
color3 #81d5cc
color4 #93cdf6
color5 #50dbcf
color6 #81d5cc
color7 #dbe4ed
color8 #8193a1
color9 #ffb4ab
color10 #50dbcf
color11 #81d5cc
color12 #93cdf6
color13 #50dbcf
color14 #81d5cc
color15 #dbe4ed

cursor                #dbe4ed
cursor_text_color     #0c141b
background            #0c141b
foreground            #dbe4ed
selection_foreground  #b7c9d8
selection_background  #384956
active_border_color   #50dbcf
inactive_border_color #384956
url_color             #50dbcf

active_tab_foreground   #003733
active_tab_background   #50dbcf
inactive_tab_foreground #b7c9d8
inactive_tab_background #384956
cursor_trail_color      #b7c9d8
