cursor #1e1a24
cursor_text_color #4d4357

foreground            #1e1a24
background            #fff7ff
selection_foreground  #ffffff
selection_background  #a4c9fe
url_color             #1a60a5

color0   #16111b
color1   #9c002f
color2   #007b10
color3   #c6bb00
color4   #1461ad
color5   #badcff
color6   #1a60a5
color7   #2b2c2e
color8   #86898c
color9   #d02c59
color10  #0db523
color11  #d6ca00
color12  #266fc8
color13  #badcff
color14  #7ca9d6
color15  #eff3f7
